# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Package
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
        with:
         name: ohazan/second-mathi-wdio   
      - run: npm install -g serve
      - run: serve &

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: sudo apt-get install chromium-browser
      - run: npm install
      - run: npx wdio
